//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windesheim.Social.UI.SocialService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialService.ISocialService")]
    public interface ISocialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Login", ReplyAction="http://tempuri.org/IAuthentication/LoginResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Windesheim.Social.Objects.FacebookLoginCredentials))]
        Windesheim.Social.Objects.Authentication Login(Windesheim.Social.Objects.LoginCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/UserHasAccess", ReplyAction="http://tempuri.org/IGroups/UserHasAccessResponse")]
        bool UserHasAccess(Windesheim.Social.Objects.Authentication auth, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/GetGroups", ReplyAction="http://tempuri.org/IGroups/GetGroupsResponse")]
        System.Collections.Generic.List<Windesheim.Social.Objects.Group> GetGroups(Windesheim.Social.Objects.Authentication auth);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialServiceChannel : Windesheim.Social.UI.SocialService.ISocialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialServiceClient : System.ServiceModel.ClientBase<Windesheim.Social.UI.SocialService.ISocialService>, Windesheim.Social.UI.SocialService.ISocialService {
        
        public SocialServiceClient() {
        }
        
        public SocialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windesheim.Social.Objects.Authentication Login(Windesheim.Social.Objects.LoginCredentials credentials) {
            return base.Channel.Login(credentials);
        }
        
        public bool UserHasAccess(Windesheim.Social.Objects.Authentication auth, int groupId) {
            return base.Channel.UserHasAccess(auth, groupId);
        }
        
        public System.Collections.Generic.List<Windesheim.Social.Objects.Group> GetGroups(Windesheim.Social.Objects.Authentication auth) {
            return base.Channel.GetGroups(auth);
        }
    }
}
