//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windesheim.Social.UI.SocialService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialService.ISocialService")]
    public interface ISocialService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentication/Login", ReplyAction="http://tempuri.org/IAuthentication/LoginResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Windesheim.Social.Objects.FacebookLoginCredentials))]
        Windesheim.Social.Objects.Authentication Login(Windesheim.Social.Objects.LoginCredentials credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/AddGroup", ReplyAction="http://tempuri.org/IGroups/AddGroupResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Windesheim.Social.Objects.GroupExtended))]
        int AddGroup(Windesheim.Social.Objects.Authentication auth, Windesheim.Social.Objects.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/GetGroups", ReplyAction="http://tempuri.org/IGroups/GetGroupsResponse")]
        System.Collections.Generic.List<Windesheim.Social.Objects.Group> GetGroups(Windesheim.Social.Objects.Authentication auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/GetGroup", ReplyAction="http://tempuri.org/IGroups/GetGroupResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Windesheim.Social.Objects.GroupExtended))]
        Windesheim.Social.Objects.Group GetGroup(Windesheim.Social.Objects.Authentication auth, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/GetGroupsExtended", ReplyAction="http://tempuri.org/IGroups/GetGroupsExtendedResponse")]
        System.Collections.Generic.List<Windesheim.Social.Objects.GroupExtended> GetGroupsExtended(Windesheim.Social.Objects.Authentication auth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/EnrollInGroup", ReplyAction="http://tempuri.org/IGroups/EnrollInGroupResponse")]
        void EnrollInGroup(Windesheim.Social.Objects.Authentication auth, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/PostMessage", ReplyAction="http://tempuri.org/IGroups/PostMessageResponse")]
        void PostMessage(Windesheim.Social.Objects.Authentication auth, Windesheim.Social.Objects.Message message, System.Nullable<int> parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/GetMessages", ReplyAction="http://tempuri.org/IGroups/GetMessagesResponse")]
        System.Collections.Generic.List<Windesheim.Social.Objects.Message> GetMessages(Windesheim.Social.Objects.Authentication auth, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/DeleteMessage", ReplyAction="http://tempuri.org/IGroups/DeleteMessageResponse")]
        void DeleteMessage(Windesheim.Social.Objects.Authentication auth, int messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroups/GetRelevantMessages", ReplyAction="http://tempuri.org/IGroups/GetRelevantMessagesResponse")]
        System.Collections.Generic.List<Windesheim.Social.Objects.Message> GetRelevantMessages(Windesheim.Social.Objects.Authentication auth, int skip, int take);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialServiceChannel : Windesheim.Social.UI.SocialService.ISocialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialServiceClient : System.ServiceModel.ClientBase<Windesheim.Social.UI.SocialService.ISocialService>, Windesheim.Social.UI.SocialService.ISocialService {
        
        public SocialServiceClient() {
        }
        
        public SocialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windesheim.Social.Objects.Authentication Login(Windesheim.Social.Objects.LoginCredentials credentials) {
            return base.Channel.Login(credentials);
        }
        
        public int AddGroup(Windesheim.Social.Objects.Authentication auth, Windesheim.Social.Objects.Group group) {
            return base.Channel.AddGroup(auth, group);
        }
        
        public System.Collections.Generic.List<Windesheim.Social.Objects.Group> GetGroups(Windesheim.Social.Objects.Authentication auth) {
            return base.Channel.GetGroups(auth);
        }
        
        public Windesheim.Social.Objects.Group GetGroup(Windesheim.Social.Objects.Authentication auth, int groupId) {
            return base.Channel.GetGroup(auth, groupId);
        }
        
        public System.Collections.Generic.List<Windesheim.Social.Objects.GroupExtended> GetGroupsExtended(Windesheim.Social.Objects.Authentication auth) {
            return base.Channel.GetGroupsExtended(auth);
        }
        
        public void EnrollInGroup(Windesheim.Social.Objects.Authentication auth, int groupId) {
            base.Channel.EnrollInGroup(auth, groupId);
        }
        
        public void PostMessage(Windesheim.Social.Objects.Authentication auth, Windesheim.Social.Objects.Message message, System.Nullable<int> parentId) {
            base.Channel.PostMessage(auth, message, parentId);
        }
        
        public System.Collections.Generic.List<Windesheim.Social.Objects.Message> GetMessages(Windesheim.Social.Objects.Authentication auth, int groupId) {
            return base.Channel.GetMessages(auth, groupId);
        }
        
        public void DeleteMessage(Windesheim.Social.Objects.Authentication auth, int messageId) {
            base.Channel.DeleteMessage(auth, messageId);
        }
        
        public System.Collections.Generic.List<Windesheim.Social.Objects.Message> GetRelevantMessages(Windesheim.Social.Objects.Authentication auth, int skip, int take) {
            return base.Channel.GetRelevantMessages(auth, skip, take);
        }
    }
}
