//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Sessions__userId__0CBAE877", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Windesheim.Social.Service.Data.Users), "Sessions", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Windesheim.Social.Service.Data.Sessions), true)]
[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Users_Gro__group__15502E78", "Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Windesheim.Social.Service.Data.Groups), "Users_Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Windesheim.Social.Service.Data.Users_Groups), true)]
[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Users_Gro__userI__145C0A3F", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Windesheim.Social.Service.Data.Users), "Users_Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Windesheim.Social.Service.Data.Users_Groups), true)]
[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Messages__groupI__1FCDBCEB", "Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Windesheim.Social.Service.Data.Groups), "Messages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Windesheim.Social.Service.Data.Messages), true)]
[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Messages__parent__21B6055D", "Messages", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Windesheim.Social.Service.Data.Messages), "Messages1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Windesheim.Social.Service.Data.Messages), true)]
[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Messages__userId__20C1E124", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Windesheim.Social.Service.Data.Users), "Messages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Windesheim.Social.Service.Data.Messages), true)]

#endregion

namespace Windesheim.Social.Service.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WindesheimSocialDatabase : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WindesheimSocialDatabase object using the connection string found in the 'WindesheimSocialDatabase' section of the application configuration file.
        /// </summary>
        public WindesheimSocialDatabase() : base("name=WindesheimSocialDatabase", "WindesheimSocialDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WindesheimSocialDatabase object.
        /// </summary>
        public WindesheimSocialDatabase(string connectionString) : base(connectionString, "WindesheimSocialDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WindesheimSocialDatabase object.
        /// </summary>
        public WindesheimSocialDatabase(EntityConnection connection) : base(connection, "WindesheimSocialDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Groups> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Groups>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Groups> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sessions> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Sessions>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Sessions> _Sessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users_Groups> Users_Groups
        {
            get
            {
                if ((_Users_Groups == null))
                {
                    _Users_Groups = base.CreateObjectSet<Users_Groups>("Users_Groups");
                }
                return _Users_Groups;
            }
        }
        private ObjectSet<Users_Groups> _Users_Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExtendedProperties> ExtendedProperties
        {
            get
            {
                if ((_ExtendedProperties == null))
                {
                    _ExtendedProperties = base.CreateObjectSet<ExtendedProperties>("ExtendedProperties");
                }
                return _ExtendedProperties;
            }
        }
        private ObjectSet<ExtendedProperties> _ExtendedProperties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Messages> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Messages>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Messages> _Messages;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Groups groups)
        {
            base.AddObject("Groups", groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Sessions sessions)
        {
            base.AddObject("Sessions", sessions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users_Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers_Groups(Users_Groups users_Groups)
        {
            base.AddObject("Users_Groups", users_Groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExtendedProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExtendedProperties(ExtendedProperties extendedProperties)
        {
            base.AddObject("ExtendedProperties", extendedProperties);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Messages messages)
        {
            base.AddObject("Messages", messages);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="ExtendedProperties")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExtendedProperties : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExtendedProperties object.
        /// </summary>
        /// <param name="extendedPropertyId">Initial value of the extendedPropertyId property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static ExtendedProperties CreateExtendedProperties(global::System.Int32 extendedPropertyId, global::System.String value)
        {
            ExtendedProperties extendedProperties = new ExtendedProperties();
            extendedProperties.extendedPropertyId = extendedPropertyId;
            extendedProperties.value = value;
            return extendedProperties;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 extendedPropertyId
        {
            get
            {
                return _extendedPropertyId;
            }
            set
            {
                if (_extendedPropertyId != value)
                {
                    OnextendedPropertyIdChanging(value);
                    ReportPropertyChanging("extendedPropertyId");
                    _extendedPropertyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("extendedPropertyId");
                    OnextendedPropertyIdChanged();
                }
            }
        }
        private global::System.Int32 _extendedPropertyId;
        partial void OnextendedPropertyIdChanging(global::System.Int32 value);
        partial void OnextendedPropertyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Groups object.
        /// </summary>
        /// <param name="groupId">Initial value of the groupId property.</param>
        /// <param name="groupName">Initial value of the groupName property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="accessType">Initial value of the accessType property.</param>
        public static Groups CreateGroups(global::System.Int32 groupId, global::System.String groupName, global::System.String description, global::System.Byte accessType)
        {
            Groups groups = new Groups();
            groups.groupId = groupId;
            groups.groupName = groupName;
            groups.description = description;
            groups.accessType = accessType;
            return groups;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 groupId
        {
            get
            {
                return _groupId;
            }
            set
            {
                if (_groupId != value)
                {
                    OngroupIdChanging(value);
                    ReportPropertyChanging("groupId");
                    _groupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("groupId");
                    OngroupIdChanged();
                }
            }
        }
        private global::System.Int32 _groupId;
        partial void OngroupIdChanging(global::System.Int32 value);
        partial void OngroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String groupName
        {
            get
            {
                return _groupName;
            }
            set
            {
                OngroupNameChanging(value);
                ReportPropertyChanging("groupName");
                _groupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("groupName");
                OngroupNameChanged();
            }
        }
        private global::System.String _groupName;
        partial void OngroupNameChanging(global::System.String value);
        partial void OngroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte accessType
        {
            get
            {
                return _accessType;
            }
            set
            {
                OnaccessTypeChanging(value);
                ReportPropertyChanging("accessType");
                _accessType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("accessType");
                OnaccessTypeChanged();
            }
        }
        private global::System.Byte _accessType;
        partial void OnaccessTypeChanging(global::System.Byte value);
        partial void OnaccessTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Users_Gro__group__15502E78", "Users_Groups")]
        public EntityCollection<Users_Groups> Users_Groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users_Groups>("WindesheimSocialEntities.FK__Users_Gro__group__15502E78", "Users_Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users_Groups>("WindesheimSocialEntities.FK__Users_Gro__group__15502E78", "Users_Groups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Messages__groupI__1FCDBCEB", "Messages")]
        public EntityCollection<Messages> Messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Messages>("WindesheimSocialEntities.FK__Messages__groupI__1FCDBCEB", "Messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Messages>("WindesheimSocialEntities.FK__Messages__groupI__1FCDBCEB", "Messages", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Messages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Messages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Messages object.
        /// </summary>
        /// <param name="messageId">Initial value of the messageId property.</param>
        /// <param name="groupId">Initial value of the groupId property.</param>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="value">Initial value of the value property.</param>
        /// <param name="postDate">Initial value of the postDate property.</param>
        public static Messages CreateMessages(global::System.Int32 messageId, global::System.Int32 groupId, global::System.Int64 userId, global::System.String value, global::System.DateTime postDate)
        {
            Messages messages = new Messages();
            messages.messageId = messageId;
            messages.groupId = groupId;
            messages.userId = userId;
            messages.value = value;
            messages.postDate = postDate;
            return messages;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 messageId
        {
            get
            {
                return _messageId;
            }
            set
            {
                if (_messageId != value)
                {
                    OnmessageIdChanging(value);
                    ReportPropertyChanging("messageId");
                    _messageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("messageId");
                    OnmessageIdChanged();
                }
            }
        }
        private global::System.Int32 _messageId;
        partial void OnmessageIdChanging(global::System.Int32 value);
        partial void OnmessageIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parent
        {
            get
            {
                return _parent;
            }
            set
            {
                OnparentChanging(value);
                ReportPropertyChanging("parent");
                _parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent");
                OnparentChanged();
            }
        }
        private Nullable<global::System.Int32> _parent;
        partial void OnparentChanging(Nullable<global::System.Int32> value);
        partial void OnparentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 groupId
        {
            get
            {
                return _groupId;
            }
            set
            {
                OngroupIdChanging(value);
                ReportPropertyChanging("groupId");
                _groupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupId");
                OngroupIdChanged();
            }
        }
        private global::System.Int32 _groupId;
        partial void OngroupIdChanging(global::System.Int32 value);
        partial void OngroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime postDate
        {
            get
            {
                return _postDate;
            }
            set
            {
                OnpostDateChanging(value);
                ReportPropertyChanging("postDate");
                _postDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("postDate");
                OnpostDateChanged();
            }
        }
        private global::System.DateTime _postDate;
        partial void OnpostDateChanging(global::System.DateTime value);
        partial void OnpostDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Messages__groupI__1FCDBCEB", "Groups")]
        public Groups Groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("WindesheimSocialEntities.FK__Messages__groupI__1FCDBCEB", "Groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("WindesheimSocialEntities.FK__Messages__groupI__1FCDBCEB", "Groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Groups> GroupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("WindesheimSocialEntities.FK__Messages__groupI__1FCDBCEB", "Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Groups>("WindesheimSocialEntities.FK__Messages__groupI__1FCDBCEB", "Groups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Messages__parent__21B6055D", "Messages1")]
        public EntityCollection<Messages> Children
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Messages>("WindesheimSocialEntities.FK__Messages__parent__21B6055D", "Messages1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Messages>("WindesheimSocialEntities.FK__Messages__parent__21B6055D", "Messages1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Messages__parent__21B6055D", "Messages")]
        public Messages parentMessage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Messages>("WindesheimSocialEntities.FK__Messages__parent__21B6055D", "Messages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Messages>("WindesheimSocialEntities.FK__Messages__parent__21B6055D", "Messages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Messages> parentMessageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Messages>("WindesheimSocialEntities.FK__Messages__parent__21B6055D", "Messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Messages>("WindesheimSocialEntities.FK__Messages__parent__21B6055D", "Messages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Messages__userId__20C1E124", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Messages__userId__20C1E124", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Messages__userId__20C1E124", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Messages__userId__20C1E124", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("WindesheimSocialEntities.FK__Messages__userId__20C1E124", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Sessions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sessions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sessions object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="ticket">Initial value of the ticket property.</param>
        /// <param name="validTill">Initial value of the validTill property.</param>
        public static Sessions CreateSessions(global::System.Int64 userId, global::System.Guid ticket, global::System.DateTime validTill)
        {
            Sessions sessions = new Sessions();
            sessions.userId = userId;
            sessions.ticket = ticket;
            sessions.validTill = validTill;
            return sessions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ticket
        {
            get
            {
                return _ticket;
            }
            set
            {
                OnticketChanging(value);
                ReportPropertyChanging("ticket");
                _ticket = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ticket");
                OnticketChanged();
            }
        }
        private global::System.Guid _ticket;
        partial void OnticketChanging(global::System.Guid value);
        partial void OnticketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime validTill
        {
            get
            {
                return _validTill;
            }
            set
            {
                OnvalidTillChanging(value);
                ReportPropertyChanging("validTill");
                _validTill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("validTill");
                OnvalidTillChanged();
            }
        }
        private global::System.DateTime _validTill;
        partial void OnvalidTillChanging(global::System.DateTime value);
        partial void OnvalidTillChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Sessions__userId__0CBAE877", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="userName">Initial value of the userName property.</param>
        public static Users CreateUsers(global::System.Int64 userId, global::System.String userName)
        {
            Users users = new Users();
            users.userId = userId;
            users.userName = userName;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> facebookId
        {
            get
            {
                return _facebookId;
            }
            set
            {
                OnfacebookIdChanging(value);
                ReportPropertyChanging("facebookId");
                _facebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("facebookId");
                OnfacebookIdChanged();
            }
        }
        private Nullable<global::System.Int64> _facebookId;
        partial void OnfacebookIdChanging(Nullable<global::System.Int64> value);
        partial void OnfacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Sessions__userId__0CBAE877", "Sessions")]
        public Sessions Sessions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sessions> SessionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Users_Gro__userI__145C0A3F", "Users_Groups")]
        public EntityCollection<Users_Groups> Users_Groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users_Groups>("WindesheimSocialEntities.FK__Users_Gro__userI__145C0A3F", "Users_Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users_Groups>("WindesheimSocialEntities.FK__Users_Gro__userI__145C0A3F", "Users_Groups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Messages__userId__20C1E124", "Messages")]
        public EntityCollection<Messages> Messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Messages>("WindesheimSocialEntities.FK__Messages__userId__20C1E124", "Messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Messages>("WindesheimSocialEntities.FK__Messages__userId__20C1E124", "Messages", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Users_Groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users_Groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users_Groups object.
        /// </summary>
        /// <param name="user_groupId">Initial value of the user_groupId property.</param>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="groupId">Initial value of the groupId property.</param>
        /// <param name="groupRole">Initial value of the groupRole property.</param>
        public static Users_Groups CreateUsers_Groups(global::System.Int64 user_groupId, global::System.Int64 userId, global::System.Int32 groupId, global::System.Byte groupRole)
        {
            Users_Groups users_Groups = new Users_Groups();
            users_Groups.user_groupId = user_groupId;
            users_Groups.userId = userId;
            users_Groups.groupId = groupId;
            users_Groups.groupRole = groupRole;
            return users_Groups;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 user_groupId
        {
            get
            {
                return _user_groupId;
            }
            set
            {
                if (_user_groupId != value)
                {
                    Onuser_groupIdChanging(value);
                    ReportPropertyChanging("user_groupId");
                    _user_groupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_groupId");
                    Onuser_groupIdChanged();
                }
            }
        }
        private global::System.Int64 _user_groupId;
        partial void Onuser_groupIdChanging(global::System.Int64 value);
        partial void Onuser_groupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                OnuserIdChanging(value);
                ReportPropertyChanging("userId");
                _userId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userId");
                OnuserIdChanged();
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 groupId
        {
            get
            {
                return _groupId;
            }
            set
            {
                OngroupIdChanging(value);
                ReportPropertyChanging("groupId");
                _groupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupId");
                OngroupIdChanged();
            }
        }
        private global::System.Int32 _groupId;
        partial void OngroupIdChanging(global::System.Int32 value);
        partial void OngroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte groupRole
        {
            get
            {
                return _groupRole;
            }
            set
            {
                OngroupRoleChanging(value);
                ReportPropertyChanging("groupRole");
                _groupRole = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupRole");
                OngroupRoleChanged();
            }
        }
        private global::System.Byte _groupRole;
        partial void OngroupRoleChanging(global::System.Byte value);
        partial void OngroupRoleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Users_Gro__group__15502E78", "Groups")]
        public Groups Groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("WindesheimSocialEntities.FK__Users_Gro__group__15502E78", "Groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("WindesheimSocialEntities.FK__Users_Gro__group__15502E78", "Groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Groups> GroupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groups>("WindesheimSocialEntities.FK__Users_Gro__group__15502E78", "Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Groups>("WindesheimSocialEntities.FK__Users_Gro__group__15502E78", "Groups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Users_Gro__userI__145C0A3F", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Users_Gro__userI__145C0A3F", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Users_Gro__userI__145C0A3F", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Users_Gro__userI__145C0A3F", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("WindesheimSocialEntities.FK__Users_Gro__userI__145C0A3F", "Users", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
