//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WindesheimSocialEntities", "FK__Sessions__userId__0CBAE877", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Windesheim.Social.Service.Data.Users), "Sessions", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Windesheim.Social.Service.Data.Sessions), true)]

#endregion

namespace Windesheim.Social.Service.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WindesheimSocialDatabase : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WindesheimSocialDatabase object using the connection string found in the 'WindesheimSocialDatabase' section of the application configuration file.
        /// </summary>
        public WindesheimSocialDatabase() : base("name=WindesheimSocialDatabase", "WindesheimSocialDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WindesheimSocialDatabase object.
        /// </summary>
        public WindesheimSocialDatabase(string connectionString) : base(connectionString, "WindesheimSocialDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WindesheimSocialDatabase object.
        /// </summary>
        public WindesheimSocialDatabase(EntityConnection connection) : base(connection, "WindesheimSocialDatabase")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Groups> Groups
        {
            get
            {
                if ((_Groups == null))
                {
                    _Groups = base.CreateObjectSet<Groups>("Groups");
                }
                return _Groups;
            }
        }
        private ObjectSet<Groups> _Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sessions> Sessions
        {
            get
            {
                if ((_Sessions == null))
                {
                    _Sessions = base.CreateObjectSet<Sessions>("Sessions");
                }
                return _Sessions;
            }
        }
        private ObjectSet<Sessions> _Sessions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroups(Groups groups)
        {
            base.AddObject("Groups", groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sessions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSessions(Sessions sessions)
        {
            base.AddObject("Sessions", sessions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Groups object.
        /// </summary>
        /// <param name="groupId">Initial value of the groupId property.</param>
        /// <param name="groupName">Initial value of the groupName property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="accessType">Initial value of the accessType property.</param>
        public static Groups CreateGroups(global::System.Int32 groupId, global::System.String groupName, global::System.String description, global::System.Byte accessType)
        {
            Groups groups = new Groups();
            groups.groupId = groupId;
            groups.groupName = groupName;
            groups.description = description;
            groups.accessType = accessType;
            return groups;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 groupId
        {
            get
            {
                return _groupId;
            }
            set
            {
                if (_groupId != value)
                {
                    OngroupIdChanging(value);
                    ReportPropertyChanging("groupId");
                    _groupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("groupId");
                    OngroupIdChanged();
                }
            }
        }
        private global::System.Int32 _groupId;
        partial void OngroupIdChanging(global::System.Int32 value);
        partial void OngroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String groupName
        {
            get
            {
                return _groupName;
            }
            set
            {
                OngroupNameChanging(value);
                ReportPropertyChanging("groupName");
                _groupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("groupName");
                OngroupNameChanged();
            }
        }
        private global::System.String _groupName;
        partial void OngroupNameChanging(global::System.String value);
        partial void OngroupNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte accessType
        {
            get
            {
                return _accessType;
            }
            set
            {
                OnaccessTypeChanging(value);
                ReportPropertyChanging("accessType");
                _accessType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("accessType");
                OnaccessTypeChanged();
            }
        }
        private global::System.Byte _accessType;
        partial void OnaccessTypeChanging(global::System.Byte value);
        partial void OnaccessTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Sessions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sessions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sessions object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="ticket">Initial value of the ticket property.</param>
        /// <param name="validTill">Initial value of the validTill property.</param>
        public static Sessions CreateSessions(global::System.Int64 userId, global::System.Guid ticket, global::System.DateTime validTill)
        {
            Sessions sessions = new Sessions();
            sessions.userId = userId;
            sessions.ticket = ticket;
            sessions.validTill = validTill;
            return sessions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ticket
        {
            get
            {
                return _ticket;
            }
            set
            {
                OnticketChanging(value);
                ReportPropertyChanging("ticket");
                _ticket = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ticket");
                OnticketChanged();
            }
        }
        private global::System.Guid _ticket;
        partial void OnticketChanging(global::System.Guid value);
        partial void OnticketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime validTill
        {
            get
            {
                return _validTill;
            }
            set
            {
                OnvalidTillChanging(value);
                ReportPropertyChanging("validTill");
                _validTill = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("validTill");
                OnvalidTillChanged();
            }
        }
        private global::System.DateTime _validTill;
        partial void OnvalidTillChanging(global::System.DateTime value);
        partial void OnvalidTillChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Sessions__userId__0CBAE877", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WindesheimSocialEntities", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of the userId property.</param>
        /// <param name="userName">Initial value of the userName property.</param>
        public static Users CreateUsers(global::System.Int64 userId, global::System.String userName)
        {
            Users users = new Users();
            users.userId = userId;
            users.userName = userName;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 userId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnuserIdChanging(value);
                    ReportPropertyChanging("userId");
                    _userId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userId");
                    OnuserIdChanged();
                }
            }
        }
        private global::System.Int64 _userId;
        partial void OnuserIdChanging(global::System.Int64 value);
        partial void OnuserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> facebookId
        {
            get
            {
                return _facebookId;
            }
            set
            {
                OnfacebookIdChanging(value);
                ReportPropertyChanging("facebookId");
                _facebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("facebookId");
                OnfacebookIdChanged();
            }
        }
        private Nullable<global::System.Int64> _facebookId;
        partial void OnfacebookIdChanging(Nullable<global::System.Int64> value);
        partial void OnfacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userName
        {
            get
            {
                return _userName;
            }
            set
            {
                OnuserNameChanging(value);
                ReportPropertyChanging("userName");
                _userName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userName");
                OnuserNameChanged();
            }
        }
        private global::System.String _userName;
        partial void OnuserNameChanging(global::System.String value);
        partial void OnuserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WindesheimSocialEntities", "FK__Sessions__userId__0CBAE877", "Sessions")]
        public Sessions Sessions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sessions> SessionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sessions>("WindesheimSocialEntities.FK__Sessions__userId__0CBAE877", "Sessions", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
